$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train
display_name: Train
version: 13
type: command
inputs:
  training_data: 
    type: uri_folder
  max_epocs:
    type: integer
  learning_rate: 
    type: number
    default: 0.01
  learning_rate_schedule: 
    type: string
    default: time-based 
outputs:
  eval_output:
    type: uri_folder
code: ./train_src
environment: azureml:environment-training@latest
command: >-
  python training_inference.py 
  --training_data ${{inputs.training_data}} 
  --max_epocs ${{inputs.max_epocs}}   
  --learning_rate ${{inputs.learning_rate}} 
  --learning_rate_schedule ${{inputs.learning_rate_schedule}} 
  --eval_output ${{outputs.model_output}}
